server:
  port: 8191
  servlet:
    context-path: /market-cart

integrations:
  product-service:
    url: http://localhost:8180/market/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000